


import type { Metadata } from "next";
import {  Poppins, Lora, Mona_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

// Montserrat for headings / logo
const monasans = Mona_Sans({
  variable: "--font-monasans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Poppins for nav links, buttons, body
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

// Lora for paragraphs or special sections
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${monasans.variable} ${poppins.variable} ${lora.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
